### ISSUE TITLE
Need a lustre-csi-driver release

### ISSUE THREAD

**Issue by magicite** [HewlettPackard/lustre-csi-driver#25]
The readme references what is in this repo as v0.0.1 but there are no branches/tags with that designation and no container in ghcr.io with that designation.

I suggest doing a release (see [here](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases)), which might also require updating the GitHub action to build and push the release.

**Comment by inf0rmatiker** [comment]
Working on providing a release for v0.0.1

**Comment by inf0rmatiker** [comment]
This has been addressed by [PR #27](https://github.com/HewlettPackard/lustre-csi-driver/pull/27)
